config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'home#feed_photo', as: :authenticated_root
    end

    unauthenticated do
      root 'home#guest_feed_photo', as: :unauthenticated_root
    end
  end

  resources :users, only: :show
  resources :photos
  resources :albums

  get 'guest-albums', to: 'home#guest_feed_album'
  get 'feed-albums', to: 'home#feed_album'
  get 'discover-photos', to: 'home#discover_photo'
  get 'discover-albums', to: 'home#discover_album'

  post 'follow', to: 'users#follow'
  post 'like', to: 'users#like'

  namespace :admin do
    resources :albums, except: [:new, :create, :show]
    resources :photos, except: [:new, :create, :show]
    resources :users, except: [:new, :create, :show]
  end

   get 'get_album', to: "users#get_album"

end

app/models/album.rb
class Album < ApplicationRecord
   belongs_to :user
   has_many :photos, dependent: :destroy

   has_many :likes, as: :likeable, dependent: :destroy

   validates :title, presence: true, length: {maximum: 140}
   validates :description, presence: true, length: {maximum: 300}
   validates :shared, inclusion: { in: [true, false]}

   before_validation :check_description

   scope :feed_album, -> (current_user) { where(user_id:current_user.followees, shared:true).or(Album.where(user_id:current_user)).order(created_at: :desc) }
   scope :discover_album, -> { where(shared:true).order(created_at: :desc) }
   scope :user_album, -> {where(shared:true).order(created_at: :desc)}

   private
     def check_description
       unless description.present?
         self.description = "This album of user who has id #{user_id}"
       end
     end

end

app/controllers/admin/albums_controller.rb
class Admin::AlbumsController < ApplicationController
  before_action :admin?

  def index
    @albums = Album.order(created_at: :desc).page(params[:page]).per(40)
  end

  def edit
    @album = Album.find(get_album)
    @photos = @album.photos
  end

  def update
    @album = Album.find(get_album)
    @photo = @album.photos.new(photo_detail)
    unless @photo.image_url.nil?
      @photo.user_id = @album.user_id
      @photo.save
    end
    if @album.update_attributes(album_detail)
      flash[:success] = "An album has been successfully updated."
      redirect_to admin_albums_path
    else
      flash[:danger] = @album.errors.full_messages[0]
      redirect_to edit_album_path(@album.id)
    end
  end

  def destroy
    @album = current_user.albums.find(params[:id])
    user_id = @album.user_id

    if @album.destroy
      flash[:success] = "Successfully deleted photo!"
      redirect_to user_path(user_id)
    else
      flash[:danger] = @album.errors.full_messages[0]
      redirect_to edit_photo_path(@album.id)
    end
  end

  protected
  def admin?
    if !current_user.admin
      redirect_to authenticated_root_path
    end
  end

  private
  def get_album
    params.require(:id)
  end

  def album_detail
    params.require(:album).permit(:title, :description, :shared)
  end

  def photo_detail
    params.require(:album).permit(:title, :description, :shared, :image)
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_detail)
    @album.user_id = current_user.id
    @photo = @album.photos.new(photo_detail)
    @photo.user_id = @album.user_id
    if @album.save && @photo.save
      flash[:success] = "New album has been successfully added."
      redirect_to user_path(current_user.id)
    else
      flash[:danger] = @photo.errors.full_messages[0]
      redirect_to action: :new
    end
  end

   def edit
     @album = current_user.albums.find(params[:id])
     @photos = @album.photos
   end

   def update
     @album = current_user.albums.find(params[:id])

     unless params[:album][:image].nil?
       @photo = @album.photos.new(photo_detail)
       @photo.album_id = @album.id
       @photo.user_id = @album.user_id
       @photo.save
     end
     if @album.update(album_detail)
       flash[:success] = "An album has been successfully updated."
       redirect_to user_path(@album.user_id)
     else
       flash[:danger] = @album.errors.full_messages[0]
       redirect_to edit_album_path(@album.id)
     end
   end

   def destroy
     @album = current_user.albums.find(params[:id])
     user_id = @album.user_id

       if @album.destroy
         flash[:success] = "Successfully deleted photo!"
         redirect_to user_path(user_id)
       else
         flash[:danger] = @album.errors.full_messages[0]
         redirect_to edit_photo_path(@album.id)
       end
   end

  private

    def album_detail
      params.require(:album).permit(:title, :description, :shared)
    end

    def photo_detail
      params.require(:album).permit(:title, :description, :shared, :image)
    end
end

app/helpers/admin/albums_helper.rb
module Admin::AlbumsHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/admin/albums/edit.html.erb
<div class="container-fluid h-100">
  <div class="row page h-100">
    <div class="col-lg-2 pt-3 justify-content-center ">
      <ul class="nav flex-lg-column pl-lg-5 pl-md-5 p-md-auto justify-content-center">
        <li class="nav-item">
          <a class="nav-link text-gray font-weight-bold" href="<%= admin_photos_path %>">Manage Photos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-color font-weight-bold" href="">Manage Albums</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-gray font-weight-bold" href="<%= admin_users_path %>">Manage User</a>
        </li>
      </ul>
    </div>
      <div class="col-lg-8 p-3 h-100">
        <div class="col bg-white h-100 px-lg-4 pb-4">
                <div class="font-weight-bold border-bottom d-flex justify-content-between align-items-center py-3">
                    <p class="h5">Edit Album </p>
                    <a class="btn avatar" href="<%= admin_albums_path %>">Back </a>
                </div>

                <% flash.each do |key, value| %>
                  <div class="alert alert-<%= key %>"><%= "#{value}" %></div>
                <% end %>

                <div class="row justify-content-between mt-3">
                    <div class="col-md-6 col-sm-12">
                      <%= form_for @album, url: admin_album_path(@album.id), html: {method: :put} do |f| %>
                        <div class="form-group">
                            <%= f.label :title %>
                            <%= f.text_field :title, placeholder: "Album Title", class:"form-control col-md-11" %>
                        </div>
                        <div class="form-group">
                            <%= f.label :shared, "Sharing mode" %> <br/>
                            <%= f.select(:shared, [['Public','true'], ['Private','false']], {}, { :class => 'col-lg-5 col-md-11 custom-select' }) %>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12 form-group">
                        <%= f.label :description %> <br/>
                        <%= f.text_area :description, rows: "5", placeholder:"Album Description", class:"form-control" %>
                    </div>
                </div>
                <div class="row mt-3 mx-1">
                  <% if @photos %>
                  <% @photos.each do |photo| %>
                  <div class="browse-field mr-3 mb-3">
                    <div class="browse-field position-relative">
                    <%= image_tag photo.image.url, class:"browse-field" %>
                    <%= link_to raw('<i class="fas fa-times fa-lg"></i>'), admin_photo_path(photo), class:"position-absolute text-dark", style:"top:3%; right:5%;",method: :delete, data: {confirm: 'Are you sure?'} %>
                    </div>
                    <!-- <i class="fas fa-times"</i> -->
                  </div>
                  <% end %>
                  <% end %>
                  <div class="form-group uploader-hold position-relative" >
                    <i class="fas fa-plus fa-lg position-absolute text-gray" style="font-size:60px; left: 38%; top:40%;"></i>
                    <%= f.file_field :image, { class:"browse-field opacity-0" } %>
                  </div>
                </div>
                <div class="row mt-3 mx-1">
                  <%= f.submit "Save", class: "btn btn-success" %>
                  <%= link_to raw('<i class="far fa-trash-alt mr-1"></i>Delete'), admin_album_path(@album.id), class: 'btn btn-danger ml-5', method: :delete, data: {confirm: 'Are you sure?'} %>
                </div>
                <% end %>
        </div>
      </div>
      <div class="col-lg-2"></div>
    </div>
  </div>

app/views/admin/albums/index.html.erb
<div class="container-fluid h-100">
  <div class="row page h-100">
    <div class="col-lg-2 pt-3 justify-content-center ">
      <ul class="nav flex-lg-column pl-lg-5 pl-md-5 p-md-auto justify-content-center">
        <li class="nav-item">
          <a class="nav-link text-gray font-weight-bold" href="<%= admin_photos_path %>">Manage Photos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-color font-weight-bold" href="">Manage Albums</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-gray font-weight-bold" href="<%= admin_users_path %>">Manage User</a>
        </li>
      </ul>
    </div>

    <div class="col-lg-8 p-3 h-100">
      <div class="col bg-white h-100 px-lg-4 pb-4">

        <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= "#{value}" %></div>
        <% end %>

        <div class="row p-3">
          <% if @albums %>
          <% @albums.each do |album| %>
          <div class="col-lg-3 col-md-3 col-sm-6 row justify-content-center mx-0 p-0 mb-5" >
            <div class=" div200 pt-3">
              <% if photos = album.photos.order(created_at: :desc) %>
              <% if photos[2] %>
              <%= image_tag photos[2].image_url, {class:"rotate10 rounded div200px", 'data-toggle':"modal", 'data-target':"#modal-album", title:album.title, desc:album.description}%>
              <% end %>
              <% if photos[1] %>
              <%= image_tag photos[1].image_url, {class:"rotate5 rounded div200px", 'data-toggle':"modal", 'data-target':"#modal-album", title:album.title, desc:album.description}%>
              <% end %>
              <%= image_tag photos[0].image_url, {class:"norotate rounded div200px", 'data-toggle':"modal", 'data-target':"#modal-album", title:album.title, desc:album.description}%>
              <% end %>
            </div>
            <div class=" align-items-center justify-content-between d-flex position-absolute bg-dark black-title-album col-11" >
              <span class="col-9 overflow "><%=album.title%></span>
              <%= link_to raw('<i class="far fa-edit fa-lg text-white"></i>'), edit_admin_album_path(album.id), class:"col-3" %>
            </div>

          </div>
          <% end %>
          <% end %>
        </div>
        <%= paginate @albums%>

      </div>
    </div>
    <div class="col-lg-2"></div>
  </div>
</div>