config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'home#feed_photo', as: :authenticated_root
    end

    unauthenticated do
      root 'home#guest_feed_photo', as: :unauthenticated_root
    end
  end

  resources :users, only: :show
  resources :photos
  resources :albums

  get 'guest-albums', to: 'home#guest_feed_album'
  get 'feed-albums', to: 'home#feed_album'
  get 'discover-photos', to: 'home#discover_photo'
  get 'discover-albums', to: 'home#discover_album'

  post 'follow', to: 'users#follow'
  post 'like', to: 'users#like'

  namespace :admin do
    resources :albums, except: [:new, :create, :show]
    resources :photos, except: [:new, :create, :show]
    resources :users, except: [:new, :create, :show]
  end

   get 'get_album', to: "users#get_album"

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  belongs_to :album, optional: true

  has_many :likes, as: :likeable, dependent: :destroy

  validates :title, presence: true, length: {maximum: 140}
  validates :description, presence: true, length: {maximum: 300}
  validates :shared, inclusion: { in: [true, false]}

  before_validation :check_description

  mount_uploader :image, ImageUploader

  scope :discover_photo, -> { where(shared:true, album_id:nil).order(created_at: :desc) }
  scope :all_photo, -> {where(album_id:nil).order(created_at: :desc)}
  scope :current_user_photo, -> {where(album_id:nil).order(created_at: :desc)}
  scope :user_photo, -> {where(shared:true, album_id:nil).order(created_at: :desc)}

  private
    def check_description
      unless description.present?
        self.description = "This photo of user who has id #{user_id}"
      end
    end


end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < ApplicationController
  before_action :admin?

  def index
    @photos = Photo.all_photo.page(params[:page]).per(40)
  end

  def edit
    @photo = Photo.find(get_photo)
  end

  def update
    @photo = Photo.find(get_photo)
    if @photo.update_attributes(photo_detail)
      flash[:success] = "A photo has been successfully updated."
      redirect_to admin_photos_path
    else
      flash[:danger] = @photo.errors.full_messages[0]
      redirect_to edit_admin_photo_path(@photo.id)
    end
  end

  def destroy
    photo = Photo.find(get_photo)
    album_id = photo.album_id
    if photo.destroy
      flash[:success] = "Successfully deleted photo!"
      if album_id
        redirect_to edit_admin_album_path(album_id)
      else
        redirect_to admin_photos_path
      end
    else
      flash[:danger] = photo.errors.full_messages[0]
      if album_id
        redirect_to edit_admin_album_path(album_id)
      else
        redirect_to edit_admin_photo_path(photo.id)
      end
    end
  end

  protected
  def admin?
    if !current_user.admin
      redirect_to authenticated_root_path
    end
  end

  private
  def get_photo
    params.require(:id)
  end

  def photo_detail
    params.require(:photo).permit(:title, :description, :image, :shared, :album_id)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_detail)
    @photo.user_id = current_user.id

    if @photo.save
      flash[:success] = "New photo has been successfully added."
      redirect_to user_path(current_user.id)
    else
      flash[:danger] = @photo.errors.full_messages[0]
      redirect_to action: :new
    end
  end

  def edit
    @photo = current_user.photos.find(params[:id])
  end

  def update
    @photo = current_user.photos.find(params[:id])

    if @photo.update_attributes(photo_detail)
      flash[:success] = "A photo has been successfully updated."
      redirect_to user_path(@photo.user_id)
    else
      flash[:danger] = @photo.errors.full_messages[0]
      redirect_to edit_photo_path(@photo.id)
    end
  end

  def destroy
    @photo = current_user.photos.find(params[:id])
    user_id = @photo.user_id
    album_id = @photo.album_id

    if @photo.destroy
      flash[:success] = "Successfully deleted photo!"
      if album_id
        redirect_to edit_album_path(album_id)
      else
        redirect_to user_path(user_id)
      end
    else
      flash[:danger] = @photo.errors.full_messages[0]
      if album_id
        redirect_to edit_album_path(album_id)
      else
        redirect_to edit_admin_photo_path(@photo.id)
      end
    end
  end

  private

  def photo_detail
    params.require(:photo).permit(:title, :description, :image, :shared, :album_id)
  end
end

app/helpers/admin/photos_helper.rb
module Admin::PhotosHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
  def liked? (user, post)
    post.likes.find_by(user_id: user)
  end
end

app/views/admin/photos/edit.html.erb
<div class="container-fluid h-100">
    <div class="row page h-100">
      <div class="col-lg-2 pt-3 justify-content-center ">
        <ul class="nav flex-lg-column pl-lg-5 pl-md-5 p-md-auto justify-content-center">
          <li class="nav-item">
            <a class="nav-link text-color font-weight-bold" href="">Manage Photos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-gray font-weight-bold" href="<%=admin_albums_path%>">Manage Albums</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-gray font-weight-bold" href="<%= admin_users_path %>">Manage User</a>
          </li>
        </ul>
      </div>
      <div class="col-lg-8 p-3 h-100">
        <div class="col bg-white h-100 px-lg-4 pb-4">
                <div class="font-weight-bold border-bottom d-flex justify-content-between align-items-center py-3">
                    <p class="h5">Edit Photo </p>
                    <a class="btn avatar" href="<%= admin_photos_path %>">Back </a>
                </div>

                <% flash.each do |key, value| %>
                  <div class="alert alert-<%= key %>"><%= "#{value}" %></div>
                <% end %>

                <div class="row justify-content-between mt-3">
                    <div class="col-md-6 col-sm-12">
                      <%= form_for @photo, url: admin_photo_path(@photo.id), html: {method: :put} do |f| %>
                        <div class="form-group">
                            <%= f.label :title %>
                            <%= f.text_field :title, placeholder: "Photo Title", class:"form-control col-md-11" %>
                        </div>
                        <div class="form-group">
                            <%= f.label :shared, "Sharing mode" %> <br/>
                            <%= f.select(:shared, [['Public','true'], ['Private','false']], {}, { :class => 'col-lg-5 col-md-11 custom-select' }) %>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12 form-group">
                        <%= f.label :description %> <br/>
                        <%= f.text_area :description, rows: "5", placeholder:"Photo Description", class:"form-control" %>
                    </div>
                </div>
                <div class="row mt-3 mx-1">
                  <%= image_tag @photo.image.url, class:"browse-field" %>
                </div>
                <div class="row mt-3 mx-1">
                  <%= f.submit "Save", class: "btn btn-success" %>
                  <%= link_to raw('<i class="far fa-trash-alt mr-1"></i>Delete'), admin_photo_path(@photo.id), class: 'btn btn-danger ml-5', method: :delete, data: {confirm: 'Are you sure?'} %>
                </div>
                <% end %>
        </div>
      </div>
      <div class="col-lg-2"></div>
    </div>
  </div>

app/views/admin/photos/index.html.erb
<div class="container-fluid h-100">
    <div class="row page h-100">
      <div class="col-lg-2 pt-3 justify-content-center ">
        <ul class="nav flex-lg-column pl-lg-5 pl-md-5 p-md-auto justify-content-center">
          <li class="nav-item">
            <a class="nav-link text-color font-weight-bold" href="">Manage Photos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-gray font-weight-bold" href="<%=admin_albums_path%>">Manage Albums</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-gray font-weight-bold" href="<%= admin_users_path %>">Manage User</a>
          </li>
        </ul>
      </div>

      <div class="col-lg-8 p-3 h-100">
        <div class="col bg-white h-100 px-lg-4 pb-4">

          <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= "#{value}" %></div>
          <% end %>

              <div class="row p-3">
                <% if @photos %>
                <% @photos.each do |photo| %>
                <div class="col-lg-3 col-md-4 col-sm-10 pl-0 mb-4">
                  <%= image_tag photo.image_url, {class:"norotate rounded"} %>
                  <div class="black-title d-flex align-items-center justify-content-between position-absolute">
                    <span class="col-9 overflow "><%=photo.title%></span>
                    <%= link_to raw('<i class="far fa-edit fa-lg text-white"></i>'), edit_admin_photo_path(photo.id), class:"col-3" %>
                  </div>
                </div>
                <% end %>
                <% end %>
              </div>
              <%= paginate @photos%>

          </div>
        </div>
        <div class="col-lg-2"></div>
    </div>
  </div>