config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'home#feed_photo', as: :authenticated_root
    end

    unauthenticated do
      root 'home#guest_feed_photo', as: :unauthenticated_root
    end
  end

  resources :users, only: :show
  resources :photos
  resources :albums

  get 'guest-albums', to: 'home#guest_feed_album'
  get 'feed-albums', to: 'home#feed_album'
  get 'discover-photos', to: 'home#discover_photo'
  get 'discover-albums', to: 'home#discover_album'

  post 'follow', to: 'users#follow'
  post 'like', to: 'users#like'

  namespace :admin do
    resources :albums, except: [:new, :create, :show]
    resources :photos, except: [:new, :create, :show]
    resources :users, except: [:new, :create, :show]
  end

   get 'get_album', to: "users#get_album"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # after_commit :send_welcome_email
  def active_for_authentication?
    super and self.active?
  end

  def send_welcome_email
    MailerJob.perform_now self
  end

  mount_uploader :avatar, ImageUploader

  devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable, :confirmable, :trackable

    has_many :photos, dependent: :destroy
    has_many :albums, dependent: :destroy

    has_many :likes, dependent: :destroy

    has_many :follower_follows, foreign_key: :followee_id, class_name: "Follow"
    has_many :followers, through: :follower_follows, source: :follower

    has_many :followee_follows, foreign_key: :follower_id, class_name: "Follow"
    has_many :followees, through: :followee_follows, source: :followee

    validates :firstname, presence: true, length: {maximum: 25}
    validates :firstname, format: { with: /\A[a-zA-Z]+\z/, message: "should contain only letters"}

    validates :lastname, presence: true, length: {maximum: 25}
    validates :lastname, format: { with: /\A[a-zA-Z]+\z/, message: "should contain only letters"}

    validates :email, uniqueness: true, presence: true, email: true, length: {maximum: 255}, case_sensitive: false

    scope :follow?, ->(user, post) { user.followees.find_by(id: post.user_id) }
    scope :normal_user, -> {where(admin:false)}

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :admin?

  def index
    @users = User.normal_user.page(params[:page]).per(30)
  end

  def edit
    @user = User.find(get_user)
  end

  def update
    @user = User.find(get_user)
    if params[:user][:password].blank?
      if @user.update_without_password(user_detail)
        flash[:success] = "Update user successfully."
        redirect_to admin_users_path
      end
    elsif @user.update(user_detail)
      flash[:success] = "Update user successfully."
      redirect_to admin_users_path
    else
      flash[:danger] = @user.errors.full_messages[0]
      redirect_to edit_admin_user_path(@user.id)
    end

  end

  def destroy
    User.find(get_user).destroy
    redirect_to admin_users_path
  end

  protected
  def admin?
    if !current_user.admin
      redirect_to authenticated_root_path
    end
  end

  private
  def get_user
    params.require(:id)
  end

  def user_detail
    params.require(:user).permit(:firstname, :lastname, :active, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: :get_album

    def new
      @user = User.new
    end

    def show
      @user = User.find(params[:id])
      @user_own_profile = @user == current_user
      if @user_own_profile
        @photos = current_user.photos.current_user_photo.page(params[:page]).per(12)
        @albums = current_user.albums.order(created_at: :desc).page(params[:page]).per(12)
        @followings = current_user.followees.order(:firstname).page(params[:page]).per(8)
        @followers = current_user.followers.order(:firstname).page(params[:page]).per(8)
      else
        @photos = @user.photos.user_photo.page(params[:page]).per(12)
        @albums = @user.albums.user_album.page(params[:page]).per(12)
        @followings = @user.followees.order(:firstname).page(params[:page]).per(8)
        @followers = @user.followers.order(:firstname).page(params[:page]).per(8)
      end
    end

    def follow
      @user = User.find(follow_user)
      follow = Follow.find_by(follower_id:current_user.id, followee_id:@user.id)
      if follow
          follow.destroy
      else
          current_user.followees << @user
      end
      render 'follow.js.erb'
    end

    def like
      like_record = Like.find_by(like_post)
      if like_record
        like_record.destroy
      else
        Like.create(like_post)
      end
      render 'like.js.erb'
    end

    def get_album
      photos = Album.find(params[:content_id]).photos
      html = String.new
      html += '<div class="carousel-item active"><img src="'+ photos.first.image.url + '" class="d-block w-100"></div>'
      photos[1..].reverse_each do |p|
        html += '<div class="carousel-item "><img src="'+ p.image.url + '" class="d-block w-100"></div>'
      end
      render :js => html
    end

    private
      def user_detail
        params.require(:user).permit(:firstname, :lastname, :email)
      end
      def follow_user
        params.require(:followee_id)
      end
      def like_post
        { :likeable_type => params.require(:type), :likeable_id => params.require(:post_id), :user_id => params.require(:user_id) }
      end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def followed? (current_user, user)
    current_user.followees.find_by(id: user)
  end

end

app/views/users/show.html.erb
<div class="container-fluid h-100">
  <div class="row page h-100">
    <div class="col-lg-2 pt-4 justify-content-center ">
      <ul class="nav flex-lg-column pl-lg-5 pl-md-5 p-md-auto justify-content-center">
        <li class="nav-item">
          <a class="nav-link text-gray font-weight-bold" href="<%=authenticated_root_path%>">Feeds</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-gray font-weight-bold" href="<%=discover_photos_path%>">Discover</a>
        </li>
      </ul>
    </div>
    <div class="col-lg-8 p-3 h-100">
      <div class="col bg-white h-100 px-lg-4">
        <div class="row p-5">
          <div class="col-lg-3 col-md-12 col-sm-12 text-center">
            <%= image_tag (if @user.avatar.file.present? then @user.avatar.url else "https://i0.wp.com/www.repol.copl.ulaval.ca/wp-content/uploads/2019/01/default-user-icon.jpg?w=415" end), { class:"rounded rounded-circle avatar-profile" } %>
          </div>
          <div class="col-lg-9 col-md-12 col-sm-12 ">
            <div class="col-12 mt-3 text-lg-left text-sm-center">
              <%if @user_own_profile %>
              <a href="<%=edit_user_registration_path%>" class="rounded-pill btn btm-sm btn-edit-profile">Edit Profile</a>
              <%if @user.admin %>
              <a href="<%=admin_photos_path%>" class="rounded-pill font-weight-bold btn btm-sm btn-primary d-lg-inline ml-lg-5">Admin Management</a>
              <% end %>
              <% elsif followed?(current_user,@user) %>
              <button type="button" class="rounded-pill followed btn btm-sm font-size p-1 " name="follow">following</button>
              <% else %>
              <button type="button" class="rounded-pill follow btn btm-sm font-size p-1 " name="follow">follow</button>
              <% end %>
            </div>
            <div class="username my-1 col-12 text-lg-left text-sm-center"><%= "#{@user.firstname} #{@user.lastname}" %></div>
            <div class="col-12">
              <nav class="p-0">
                <div class="nav nav-tab p-0 justify-content-center justify-content-lg-start" id="nav-tab" role="tablist">

                  <a class="nav-item font-profile-tab nav-link border-0 active" id="photo-tab" data-toggle="tab" href="#nav-photo" role="tab" aria-controls="nav-photo" aria-selected="true">
                    <%=@user.photos.where(album_id:nil).count%> <span class="font-size">PHOTOS</span>
                  </a>

                  <a class="nav-item font-profile-tab nav-link border-0 " id="album-tab" data-toggle="tab" href="#nav-album" role="tab" aria-controls="nav-album" aria-selected="false">
                    <%=@user.albums.count%> <span class="font-size">ALBUMS</span>
                  </a>

                  <a class="nav-item font-profile-tab nav-link " id="following-tab" data-toggle="tab" href="#nav-following" role="tab" aria-controls="nav-following" aria-selected="false">
                    <%=@user.followees.count%> <span class="font-size">FOLLOWINGS</span>
                  </a>

                  <a class="nav-item font-profile-tab nav-link " id="follower-tab" data-toggle="tab" href="#nav-follower" role="tab" aria-controls="nav-follower" aria-selected="false">
                    <%=@user.followers.count%> <span class="font-size">FOLLOWERS</span>
                  </a>

                </div>
              </nav>
            </div>
          </div>
        </div>


        <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= "#{value}" %></div>
        <% end %>

        <div class="tab-content" id="nav-tabContent">
          <!-- PHOTOS -->
          <div class="row mt-3 px-2 tab-pane fade show active" id="nav-photo" role="tabpanel" aria-labelledby="photo-tab">
            <div class="row justify-content-end px-5 mb-3">
              <% if @user_own_profile %>
              <a href="<%=new_photo_path%>" class="rounded-pill btn btm-sm btn-add-photo btn-success" role="button"> Add Photo </a>
              <%end%>
            </div>
            <div class="row">
              <% if @photos %>
              <% @photos.each do |photo| %>
              <div class="col-lg-3 col-md-3 col-sm-6">
                <%if @user_own_profile %>
                <a href="<%= edit_photo_path(photo.id) %>" class="rounded-pill btn btm-sm btn-edit-photo" role="button"> EDIT </a>
                <%end%>
                <%= image_tag(photo.image_url, class:"rounded mx-auto d-block div200px", 'data-toggle':"modal", 'data-target':"#modal-photo", 'title': photo.title, 'desc': photo.description)%>
                <%if photo.shared == false %>
                <a href="" class="rounded-pill btn btm-sm btn-privacy" role="button"> <i class="fas fa-lock"></i> </a>
                <%end%>
                <p class="font-size text-center mt-1 mb-4"><%= photo.title %></p>
              </div>
              <% end %>
              <% end %>
            </div>
            <div class="row justify-content-center m-2">
            <%= paginate @photos%>
            </div>
          </div>
          <!-- ALBUMS -->
          <div class="row mt-3 px-2 tab-pane fade " id="nav-album" role="tabpanel" aria-labelledby="album-tab">
            <div class="row justify-content-end px-5 mb-3">
              <% if @user_own_profile %>
              <a href="<%=new_album_path%>" class="rounded-pill btn btm-sm btn-add-photo btn-success" role="button"> Add Album </a>
              <%end%>
            </div>
            <div class="row">
              <% if @albums %>
              <% @albums.each do |album| %>
              <div class="col-lg-3 col-md-3 col-sm-6 p-3 text-center" >
                <% if photos = album.photos.order(created_at: :desc) %>
                <% if photos[2] %>
                <%= image_tag photos[2].image_url, {class:"rotate10 rounded ",'data-toggle':"modal", 'data-target':"#modal-album", title:album.title, desc:album.description, onclick:"modal_album(#{album.id})"}%>
                <% end %>
                <% if photos[1] %>
                <%= image_tag photos[1].image_url, {class:"rotate5 rounded ", 'data-toggle':"modal", 'data-target':"#modal-album", title:album.title, desc:album.description, onclick:"modal_album(#{album.id})"}%>
                <% end %>
                <%= image_tag photos[0].image_url, {class:"norotate rounded ",'data-toggle':"modal", 'data-target':"#modal-album", title:album.title, desc:album.description, onclick:"modal_album(#{album.id})"}%>
                <% end %>

                <%if @user_own_profile %>
                <a href="<%= edit_album_path(album.id) %>" class="rounded-pill btn btm-sm btn-edit-photo" role="button"> EDIT </a>
                <%end%>

                <%if album.shared == false %>
                <a href="" class="rounded-pill btn btm-sm btn-privacy" role="button"> <i class="fas fa-lock"></i> </a>
                <%end%>
                <p class="photo-count p-2 position-absolute font-profile-tab"><%=album.photos.count%><br><span class="font-size">PHOTOS</span></p>

                <p class="font-size text-center mt-2 mb-4"><%= album.title %></p>
              </div>
              <% end %>
              <% end %>
            </div>
            <div class="row justify-content-center m-2">
            <%= paginate @albums%>
            </div>
          </div>
          <!-- FOLLOWINGS -->
          <div class="row mt-3 px-2 tab-pane fade" id="nav-following" role="tabpanel" aria-labelledby="following-tab">

            <div class="row px-lg-3">
              <% if @followings %>
              <% @followings.each do |following| %>

              <div class="col-sm-11 col-md-5 col-lg-3" >
                <div class="col page py-3 shadow-sm mb-4">
                  <% if following.avatar.file.nil? %>
                  <a class="btn div100px font-weight-bold rounded-circle p-2 avatar mx-auto d-block text-center" style="font-size: 50px;" type="button" href="<%=user_path(following.id)%>"><%= "#{following.firstname[0]}#{following.lastname[0]}"%></a>
                  <% else %>
                  <a href="<%=user_path(following.id)%>" ><%= image_tag following.avatar.url, { class:"rounded-circle div100px mx-auto d-block "}%></a>
                  <% end%>

                  <a class=" text-center font-weight-bold text-dark my-2 text-decoration-none h5 mx-auto d-block" href="<%=user_path(following.id)%>"><%= "#{following.firstname} #{following.lastname}" %></a>
                  <div class="row justify-content-around my-1">
                    <div class="col-5 ">
                      <p class="text-color font-tab-header font-weight-bold text-center" ><%=following.photos.count%> <br><span class="font-size">PHOTOS</span></p>
                    </div>
                    <div class="col-5 ">
                      <p class="text-color font-tab-header font-weight-bold text-center" ><%=following.albums.count%> <br><span class="font-size">ALBUMS</span></p>
                    </div>
                  </div>
                  <div class="text-center my-1">
                    <% if @user_own_profile || followed?(current_user, following) %>
                    <%= link_to "following", follow_path(followee_id:following.id), method: :post, remote: true, name:"follow", class:"rounded-pill followed btn btm-sm font-size p-1 ml-auto" %>
                    <% elsif current_user == following %>
                    <%= link_to "following", follow_path(followee_id:following.id), method: :post, remote: true, name:"follow", class:"rounded-pill followed btn btm-sm font-size p-1 ml-auto invisible" %>
                    <% else %>
                    <%= link_to "follow", follow_path(followee_id:following.id), method: :post, remote: true, name:"follow", class:"rounded-pill follow btn btm-sm font-size p-1 ml-auto"%>
                    <% end %>
                  </div>
                </div>
              </div>
              <% end %>
              <% end %>
            </div>
            <div class="row justify-content-center m-2">
            <%= paginate @followings%>
            </div>

          </div>
          <!-- FOLLOWERS -->
          <div class="row mt-3 px-2 tab-pane fade " id="nav-follower" role="tabpanel" aria-labelledby="follower-tab">

            <div class="row px-lg-3">
              <% if @followers %>
              <% @followers.each do |follower| %>

              <div class="col-sm-11 col-md-5 col-lg-3" >
                <div class="col page py-3 shadow-sm mb-4">
                  <% if follower.avatar.file.nil? %>
                  <a class="btn div100px font-weight-bold rounded-circle p-2 avatar mx-auto d-block text-center" style="font-size: 50px;" type="button" href="<%=user_path(follower.id)%>"><%= "#{follower.firstname[0]}#{follower.lastname[0]}"%></a>
                  <% else %>
                  <a href="<%=user_path(follower.id)%>" ><%= image_tag follower.avatar.url, { class:"rounded-circle div100px mx-auto d-block "}%></a>
                  <% end%>

                  <a class=" text-center font-weight-bold text-dark my-2 text-decoration-none h5 mx-auto d-block" href="<%=user_path(follower.id)%>"><%= "#{follower.firstname} #{follower.lastname}" %></a>
                  <div class="row justify-content-around my-1">
                    <div class="col-5 ">
                      <p class="text-color font-tab-header font-weight-bold text-center" ><%=follower.photos.count%> <br><span class="font-size">PHOTOS</span></p>
                    </div>
                    <div class="col-5 ">
                      <p class="text-color font-tab-header font-weight-bold text-center" ><%=follower.albums.count%> <br><span class="font-size">ALBUMS</span></p>
                    </div>
                  </div>
                  <div class="text-center my-1">
                    <% if followed?(current_user, follower) %>
                    <%= link_to "following", follow_path(followee_id:follower.id), method: :post, remote: true, name:"follow", class:"rounded-pill followed btn btm-sm font-size p-1 ml-auto"%>
                    <% elsif current_user == follower %>
                    <%= link_to "following", follow_path(followee_id:follower.id), method: :post, remote: true, name:"follow", class:"rounded-pill followed btn btm-sm font-size p-1 ml-auto invisible" %>
                    <% else %>
                    <%= link_to "follow", follow_path(followee_id:follower.id), method: :post, remote: true, name:"follow", class:"rounded-pill follow btn btm-sm font-size p-1 ml-auto"%>
                    <% end %>
                  </div>
                </div>
              </div>
              <% end %>
              <% end %>
            </div>
            <div class="row justify-content-center m-2">
            <%= paginate @followers%>
            </div>
          </div>

        </div>
      </div>
    </div>
    <div class="col-lg-2 col-md-2"></div>
  </div>
</div>
<%= render "home/modal" %>