config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'home#feed_photo', as: :authenticated_root
    end

    unauthenticated do
      root 'home#guest_feed_photo', as: :unauthenticated_root
    end
  end

  resources :users, only: :show
  resources :photos
  resources :albums

  get 'guest-albums', to: 'home#guest_feed_album'
  get 'feed-albums', to: 'home#feed_album'
  get 'discover-photos', to: 'home#discover_photo'
  get 'discover-albums', to: 'home#discover_album'

  post 'follow', to: 'users#follow'
  post 'like', to: 'users#like'

  namespace :admin do
    resources :albums, except: [:new, :create, :show]
    resources :photos, except: [:new, :create, :show]
    resources :users, except: [:new, :create, :show]
  end

   get 'get_album', to: "users#get_album"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:guest_feed_photo, :guest_feed_album]

  def feed_photo
    @photos = FeedPhoto.new(current_user).call.page(params[:page]).per(8)
  end
  def feed_album
    @albums = Album.feed_album(current_user).page(params[:page]).per(8)
  end

  def discover_photo
    @photos = Photo.discover_photo.page(params[:page]).per(8)
  end
  def discover_album
    @albums = Album.discover_album.page(params[:page]).per(8)
  end

  def guest_feed_photo
    @photos = Photo.discover_photo.page(params[:page]).per(8)
  end
  def guest_feed_album
    @albums = Album.discover_album.page(params[:page]).per(8)
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_modal.html.erb
<div id="modal-photo" class="modal" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <p class="modal-title font-weight-bold" id="modal-photo-title"></p>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body my-2 pb-5">
        <img src="" class="w-100 h-100" id="modal-photo-body"/>
        <div id="modal-photo-description" class="mb-3 mt-2"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="modal" id="modal-album" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <p class="modal-title font-weight-bold" id="modal-album-title"></p>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="albumDis" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">

          </div>
          <a class="carousel-control-prev" href="#albumDis" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#albumDis" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>

          <p id="modal-album-description" ></p>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
function modal_album(album_id) {
  var container = $(".carousel-inner");
  $.get("get_album.js", {content_id: album_id}, function() {
  }).done(function(data) {
    container.html(data);
  })
}
</script>

app/views/home/discover_album.html.erb
<div class="container-fluid h-100">
  <div class="row page h-100">
    <div class="col-lg-2 pt-4 justify-content-center ">
      <ul class="nav flex-lg-column pl-lg-5 p-md-auto justify-content-center">
        <li class="nav-item">
          <a class="nav-link text-gray font-weight-bold" href="<%=authenticated_root_path%>">Feeds</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-color font-weight-bold" href="">Discover</a>
        </li>
      </ul>
    </div>
    <div class="col-lg-8 p-3 h-100">
      <div class="col bg-white h-100">
        <div class="row justify-content-center">
          <div class="row m-3 btn-group">
            <a href="<%=discover_photos_path%>" class="btn rounded-left text-color font-weight-bold" role="button" id="photo-option"> PHOTO </a>
            <a href="" class="btn rounded-right avatar font-weight-bold" role="button" id="album-option"> ALBUM </a>
          </div>
        </div>

        <div class="row">
          <% if @albums %>
          <% @albums.each do |album| %>
          <div class="col-lg-6 col-sm-12 col-md-6 p-3 d-lg-inline-flex" >
            <div class="col-lg-6 col-sm-12 col-md-12 box-shadow position-relative p-4 text-center page">

              <% if photos = album.photos %>
              <% if photos[2] %>
              <%= image_tag photos[2].image_url, {class:"rotate10 rounded ",'data-toggle':"modal", 'data-target':"#modal-album", title:album.title, desc:album.description, onclick:"modal_album(#{album.id})"}%>
              <% end %>
              <% if photos[1] %>
              <%= image_tag photos[1].image_url, {class:"rotate5 rounded ", 'data-toggle':"modal", 'data-target':"#modal-album", title:album.title, desc:album.description, onclick:"modal_album(#{album.id})"}%>
              <% end %>
              <%= image_tag photos[0].image_url, {class:"norotate rounded ",'data-toggle':"modal", 'data-target':"#modal-album", title:album.title, desc:album.description, onclick:"modal_album(#{album.id})"}%>
              <% end %>
            </div>
            <div class="col-lg-6 p-2 col-sm-12 col-md-12 page d-block box-shadow position-relative" >
              <div class="container h-100">
                <div class="d-flex align-items-center mb-2">
                  <% if album.user.avatar.file.nil? %>
                  <a class="btn avatar font-weight-bold rounded-circle p-2" type="button" href="<%=user_path(album.user_id)%>"><%= "#{album.user.firstname[0]}#{album.user.lastname[0]}"%></a>
                  <% else %>
                  <a href="<%=user_path(album.user_id)%>" ><%= image_tag album.user.avatar.url, { style:"height:40px;width:40px;",class:"rounded-circle"}%></a>
                  <% end%>
                  <a class="font-weight-bold text-color ml-2 text-decoration-none" href="<%=user_path(album.user_id)%>"><%= "#{album.user.firstname} #{album.user.lastname}" %></a>
                  <%if album.user_id != current_user.id %>
                  <% if followed?(current_user,album.user) %>
                  <%= link_to "following", follow_path(followee_id:album.user_id), method: :post, remote: true, name:"follow", class:"rounded-pill followed btn btm-sm font-size-sm p-1 ml-auto font-weigth-bold"%>
                  <% else %>
                  <%= link_to "follow", follow_path(followee_id:album.user_id), method: :post, remote: true, name:"follow", class:"rounded-pill follow btn btm-sm font-size-sm p-1 ml-auto font-weigth-bold"%>
                  <% end %>
                  <% end %>
                </div>

                <span><b><%=album.title%></b></span>
                <p class=" font-size"><%=album.description%></p>
                <div>
                  <% if liked?(current_user, album) %>
                  <%= link_to raw('<i class="fas fa-heart text-color"></i>'), like_path(type:'Album', post_id: album.id, user_id: current_user.id), method: :post, remote: true, name:"like" %>
                  <% else %>
                  <%= link_to raw('<i class="fas fa-heart text-gray"></i>'), like_path(type:'Album', post_id: album.id, user_id: current_user.id), method: :post, remote: true, name:"like" %>
                  <% end %>
                  <span class="font-size-sm"><%= album.likes.size %> </span>
                  <span class="float-right"><small class="text-secondary "><%= album.created_at.strftime("%I:%M %p %-d/%-m/%Y") %></small></span>
                </div>
              </div>
            </div>
          </div>
          <% end %>
          <% end %>

        </div>
        <div class="row justify-content-center m-2">
          <%= paginate @albums%>
        </div>

      </div>
    </div>
    <div class="col-lg-2"></div>
  </div>
</div>

<%= render "modal" %>

app/views/home/discover_photo.html.erb
    <div class="container-fluid h-100">
        <div class="row page h-100">
          <div class="col-lg-2 pt-4 justify-content-center ">
            <ul class="nav flex-lg-column pl-lg-5 p-md-auto justify-content-center">
              <li class="nav-item">
                <a class="nav-link text-gray font-weight-bold" href="<%=authenticated_root_path%>">Feeds</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-color font-weight-bold" href="">Discover</a>
              </li>
            </ul>
          </div>
            <div class="col-lg-8 p-3 h-100">
              <div class="col bg-white h-100">
                <div class="row justify-content-center">
                  <div class="row m-3 btn-group">
                    <a href="" class="btn rounded-left avatar font-weight-bold" role="button" id="photo-option"> PHOTO </a>
                    <a href="<%=discover_albums_path%>" class="btn rounded-right text-color font-weight-bold" role="button" id="album-option"> ALBUM </a>
                  </div>
                </div>
                    <div class="row">
                      <% if @photos %>
                       <% @photos.each do |photo| %>
                       <div class="col-lg-6 col-sm-12 col-md-6 p-3 d-lg-inline-flex" >
                        <div class="col-lg-6 col-sm-12 col-md-12 p-0 box-shadow">
                         <%= image_tag(photo.image_url, 'title': photo.title, 'desc': photo.description, style:"width:100%;height:260px;cursor:pointer", 'data-toggle':"modal", 'data-target':"#modal-photo") %>
                        </div>
                        <div class="col-lg-6 p-2 col-sm-12 col-md-12 page d-block box-shadow">
                          <div class="container h-100">
                            <div class="d-flex align-items-center mb-2">

                              <% if photo.user.avatar.file.nil? %>
                              <a class="btn avatar font-weight-bold rounded-circle p-2" type="button" href="<%=user_path(photo.user_id)%>"><%= "#{photo.user.firstname[0]}#{photo.user.lastname[0]}"%></a>
                              <% else %>
                              <a href="<%=user_path(photo.user_id)%>" class="rounded-circle" ><%= image_tag photo.user.avatar.url, { style:"height:40px;width:40px;",class:"rounded-circle"}%></a>
                              <% end%>

                              <a class="font-weight-bold text-color ml-2 text-decoration-none" href="<%=user_path(photo.user_id)%>"><%= "#{photo.user.firstname} #{photo.user.lastname}" %></a>
                              <% if photo.user_id != current_user.id %>

                              <% if followed?(current_user,photo.user) %>
                              <%= link_to "following", follow_path(followee_id:photo.user_id), method: :post, remote: true, name:"follow", class:"rounded-pill followed btn btm-sm font-size-sm p-1 ml-auto font-weigth-bold"%>
                              <% else %>
                              <%= link_to "follow", follow_path(followee_id:photo.user_id), method: :post, remote: true, name:"follow", class:"rounded-pill follow btn btm-sm font-size-sm p-1 ml-auto font-weigth-bold"%>
                              <% end %>

                              <% end %>
                            </div>

                            <span><b><%=photo.title%></b></span>
                            <p class="font-size"><%=photo.description%></p>
                            <div>
                              <% if liked?(current_user, photo) %>
                              <%= link_to raw('<i class="fas fa-heart text-color"></i>'), like_path(type:'Photo', post_id: photo.id, user_id: current_user.id), method: :post, remote: true, name:"like" %>
                              <% else %>
                              <%= link_to raw('<i class="fas fa-heart text-gray"></i>'), like_path(type:'Photo', post_id: photo.id, user_id: current_user.id), method: :post, remote: true, name:"like" %>
                              <% end %>
                               <span class="font-size-sm"><%= photo.likes.size %> </span>
                              <span class="float-right"><small class="text-secondary "><%= photo.created_at.strftime("%I:%M %p %-d/%-m/%Y") %></small></span>
                            </div>
                          </div>
                        </div>
                      </div>
                      <% end %>
                    <% end %>
                </div>
                <div class="row justify-content-center m-2">
                <%= paginate @photos%>
                </div>
              </div>
            </div>
            <div class="col-lg-2"></div>
        </div>
    </div>

  <%= render "modal" %>

app/views/home/feed_album.html.erb
<div class="container-fluid h-100">
  <div class="row page h-100">
    <div class="col-lg-2 pt-4 justify-content-center ">
      <ul class="nav flex-lg-column pl-lg-5 p-md-auto justify-content-center">
        <li class="nav-item">
          <a class="nav-link text-color font-weight-bold" href="">Feeds</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-gray font-weight-bold" href="<%=discover_photos_path%>">Discover</a>
        </li>
      </ul>
    </div>
    <div class="col-lg-8 p-3 h-100">
      <div class="col bg-white h-100">
        <div class="row justify-content-center">
          <div class="row m-3 btn-group">
            <a href="<%=authenticated_root_path%>" class="btn rounded-left text-color font-weight-bold" role="button" id="photo-option"> PHOTO </a>
            <a href="" class="btn rounded-right avatar font-weight-bold" role="button" id="album-option"> ALBUM </a>
          </div>
        </div>

        <div class="row">
          <% if @albums %>
          <% @albums.each do |album| %>
          <div class="col-lg-6 col-sm-12 col-md-6 p-3 d-lg-inline-flex" >
            <div class="col-lg-6 col-sm-12 col-md-12 box-shadow position-relative p-4 text-center page">

              <% if photos = album.photos %>
              <% if photos[2] %>
              <%= image_tag photos[2].image_url, {class:"rotate10 rounded ",'data-toggle':"modal", 'data-target':"#modal-album", title:album.title, desc:album.description, onclick:"modal_album(#{album.id})"}%>
              <% end %>
              <% if photos[1] %>
              <%= image_tag photos[1].image_url, {class:"rotate5 rounded ", 'data-toggle':"modal", 'data-target':"#modal-album", title:album.title, desc:album.description, onclick:"modal_album(#{album.id})"}%>
              <% end %>
              <%= image_tag photos[0].image_url, {class:"norotate rounded ",'data-toggle':"modal", 'data-target':"#modal-album", title:album.title, desc:album.description, onclick:"modal_album(#{album.id})"}%>
              <% end %>
            </div>
            <div class="col-lg-6 p-2 col-sm-12 col-md-12 page d-block box-shadow position-relative border-left-0">
              <div class="container h-100">
                <div class="d-flex align-items-center mb-2">
                  <% if album.user.avatar.file.nil? %>
                  <a class="btn avatar font-weight-bold rounded-circle p-2" type="button" href="<%=user_path(album.user_id)%>"><%= "#{album.user.firstname[0]}#{album.user.lastname[0]}"%></a>
                  <% else %>
                  <a href="<%=user_path(album.user_id)%>" ><%= image_tag album.user.avatar.url, { style:"height:40px;width:40px;",class:"rounded-circle"}%></a>
                  <% end%>
                  <a class="font-weight-bold text-color ml-2 text-decoration-none" href="<%=user_path(album.user_id)%>"><%= "#{album.user.firstname} #{album.user.lastname}" %></a>
                </div>

                <span><b><%=album.title%></b></span>
                <p class=" font-size"><%=album.description%></p>
                <div>
                  <% if liked?(current_user, album) %>
                  <%= link_to raw('<i class="fas fa-heart text-color"></i>'), like_path(type:'Album', post_id: album.id, user_id: current_user.id), method: :post, remote: true, name:"like" %>
                  <% else %>
                  <%= link_to raw('<i class="fas fa-heart text-gray"></i>'), like_path(type:'Album', post_id: album.id, user_id: current_user.id), method: :post, remote: true, name:"like" %>
                  <% end %>
                  <span class="font-size-sm"><%= album.likes.size %> </span>
                  <span class="float-right"><small class="text-secondary "><%= album.created_at.strftime("%I:%M %p %-d/%-m/%Y") %></small></span>
                </div>
              </div>
            </div>
          </div>
          <% end %>
          <% end %>
        </div>
        <div class="row justify-content-center m-2">
          <%= paginate @albums%>
        </div>
      </div>
    </div>
    <div class="col-lg-2"></div>
  </div>
</div>

<%= render "modal" %>

app/views/home/feed_photo.html.erb
    <div class="container-fluid h-100">
        <div class="row page h-100">
          <div class="col-lg-2 col-md-2 pt-4 justify-content-center ">
            <ul class="nav flex-lg-column pl-lg-5 pl-md-5 p-md-auto justify-content-center">
              <li class="nav-item">
                <a class="nav-link text-color font-weight-bold" href="">Feeds</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-gray font-weight-bold" href="<%=discover_photos_path%>">Discover</a>
              </li>
            </ul>
          </div>
            <div class="col-lg-8 col-md-8 p-3 h-100">
              <div class="col bg-white h-100">
                <div class="row justify-content-center">
                  <div class="row m-3 btn-group">
                    <a href="" class="btn rounded-left avatar font-weight-bold" role="button" id="photo-option"> PHOTO </a>
                    <a href="<%=feed_albums_path%>" class="btn rounded-right text-color font-weight-bold" role="button" id="album-option"> ALBUM </a>
                  </div>
                </div>

                    <div class="row">
                      <% if @photos %>
                       <% @photos.each do |photo| %>
                       <div class="col-lg-6 col-sm-12 col-md-6 p-3 d-lg-inline-flex" >
                        <div class="col-lg-6 col-sm-12 col-md-12 p-0 box-shadow">
                         <%= image_tag(photo.image_url, 'title': photo.title, 'desc': photo.description, style:"width:100%;height:260px;cursor:pointer", 'data-toggle':"modal", 'data-target':"#modal-photo") %>
                        </div>
                        <div class="col-lg-6 p-2 col-sm-12 col-md-12 page d-block box-shadow">
                          <div class="container h-100">
                            <div class="d-flex align-items-center mb-2">

                              <% if photo.user.avatar.file.nil? %>
                              <a class="btn avatar font-weight-bold rounded-circle p-2" type="button" href="<%=user_path(photo.user_id)%>"><%= "#{photo.user.firstname[0]}#{photo.user.lastname[0]}"%></a>
                              <% else %>
                              <a href="<%=user_path(photo.user_id)%>" ><%= image_tag photo.user.avatar.url, { style:"height:40px;width:40px;",class:"rounded-circle"}%></a>
                              <% end%>

                              <a class="font-weight-bold text-color ml-2 text-decoration-none" href="<%=user_path(photo.user_id)%>"><%= "#{photo.user.firstname} #{photo.user.lastname}" %></a>

                            </div>

                            <span><b><%=photo.title%></b></span>
                            <p class="font-size"><%=photo.description%></p>
                            <div>
                              <% if liked?(current_user, photo) %>
                              <%= link_to raw('<i class="fas fa-heart text-color"></i>'), like_path(type:'Photo', post_id: photo.id, user_id: current_user.id), method: :post, remote: true, name:"like" %>
                              <% else %>
                              <%= link_to raw('<i class="fas fa-heart text-gray"></i>'), like_path(type:'Photo', post_id: photo.id, user_id: current_user.id), method: :post, remote: true, name:"like" %>
                              <% end %>
                               <span class="font-size-sm"><%= photo.likes.size %> </span>
                              <span class="float-right"><small class="text-secondary "><%= photo.created_at.strftime("%I:%M %p %-d/%-m/%Y") %></small></span>
                            </div>
                          </div>
                        </div>
                      </div>
                      <% end %>
                    <% end %>
                </div>
                <div class="row justify-content-center m-2">
                <%= paginate @photos%>
                </div>
              </div>
            </div>
            <div class="col-lg-2"></div>
        </div>
    </div>

  <%= render "modal" %>

app/views/home/guest_feed_album.html.erb
<div class="container-fluid h-100">
  <div class="row page h-100">
    <div class="col-lg-2 pt-4 justify-content-center ">
      <ul class="nav flex-lg-column pl-lg-5 p-md-auto justify-content-center">
        <li class="nav-item">
          <a class="nav-link text-gray font-weight-bold" href="<%=authenticated_root_path%>">Feeds</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-color font-weight-bold" href="">Discover</a>
        </li>
      </ul>
    </div>
    <div class="col-lg-8 p-3 h-100">
      <div class="col bg-white h-100">
        <div class="row justify-content-center">
          <div class="row m-3 btn-group">
            <a href="<%=unauthenticated_root_path%>" class="btn rounded-left text-color font-weight-bold" role="button" id="photo-option"> PHOTO </a>
            <a href="" class="btn rounded-right avatar font-weight-bold" role="button" id="album-option"> ALBUM </a>
          </div>
        </div>

        <div class="row">
          <% if @albums %>
          <% @albums.each do |album| %>
          <div class="col-lg-6 col-sm-12 col-md-6 p-3 d-lg-inline-flex" >
            <div class="col-lg-6 col-sm-12 col-md-12 box-shadow position-relative p-4 text-center page">

              <% if photos = album.photos %>
              <% if photos[2] %>
              <%= image_tag photos[2].image_url, {class:"rotate10 rounded ",'data-toggle':"modal", 'data-target':"#modal-album", title:album.title, desc:album.description, onclick:"modal_album(#{album.id})"}%>
              <% end %>
              <% if photos[1] %>
              <%= image_tag photos[1].image_url, {class:"rotate5 rounded ", 'data-toggle':"modal", 'data-target':"#modal-album", title:album.title, desc:album.description, onclick:"modal_album(#{album.id})"}%>
              <% end %>
              <%= image_tag photos[0].image_url, {class:"norotate rounded ",'data-toggle':"modal", 'data-target':"#modal-album", title:album.title, desc:album.description, onclick:"modal_album(#{album.id})"}%>
              <% end %>
            </div>
            <div class="col-lg-6 p-2 col-sm-12 col-md-12 page d-block box-shadow position-relative border-left-0">
              <div class="container h-100">
                <div class="d-flex align-items-center mb-2">
                  <% if album.user.avatar.file.nil? %>
                  <a class="btn avatar font-weight-bold rounded-circle p-2" type="button" href="<%=user_path(album.user_id)%>"><%= "#{album.user.firstname[0]}#{album.user.lastname[0]}"%></a>
                  <% else %>
                  <a href="<%=user_path(album.user_id)%>" ><%= image_tag album.user.avatar.url, { style:"height:40px;width:40px;",class:"rounded-circle"}%></a>
                  <% end%>
                  <a class="font-weight-bold text-color ml-2 text-decoration-none" href="<%=user_path(album.user_id)%>"><%= "#{album.user.firstname} #{album.user.lastname}" %></a>
                </div>

                <span><b><%=album.title%></b></span>
                <p class=" font-size"><%=album.description%></p>
                <div>
                  <span class=<%= if liked?(current_user, album) then "text-color" else "text-gray" end%> ><i class="fas fa-heart"></i></span>
                  <span class="font-size-sm"><%= album.likes.size %> </span>
                  <span class="float-right"><small class="text-secondary "><%= album.created_at.strftime("%I:%M %p %-d/%-m/%Y") %></small></span>
                </div>
              </div>
            </div>
          </div>
          <% end %>
          <% end %>
        </div>
        <div class="row justify-content-center m-2">
          <%= paginate @albums%>
        </div>
      </div>
    </div>
    <div class="col-lg-2"></div>
  </div>
</div>

<%= render "modal" %>

app/views/home/guest_feed_photo.html.erb
    <div class="container-fluid h-100">
        <div class="row page h-100">
          <div class="col-lg-2 pt-4 justify-content-center ">
            <ul class="nav flex-lg-column pl-lg-5 p-md-auto justify-content-center">
              <li class="nav-item">
                <a class="nav-link text-gray font-weight-bold" href="<%=authenticated_root_path%>">Feeds</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-color font-weight-bold" href="">Discover</a>
              </li>
            </ul>
          </div>
            <div class="col-lg-8 p-3 h-100">
              <div class="col bg-white h-100">
                <div class="row justify-content-center">
                  <div class="row m-3 btn-group">
                    <a href="" class="btn rounded-left avatar font-weight-bold" role="button" id="photo-option"> PHOTO </a>
                    <a href="<%=guest_albums_path%>" class="btn rounded-right text-color font-weight-bold" role="button" id="album-option"> ALBUM </a>
                  </div>
                </div>
                    <div class="row">
                      <% if @photos %>
                       <% @photos.each do |photo| %>
                       <div class="col-lg-6 col-sm-12 col-md-6 p-3 d-lg-inline-flex" >
                        <div class="col-lg-6 col-sm-12 col-md-12 p-0 box-shadow">
                         <%= image_tag(photo.image_url, 'title': photo.title, 'desc': photo.description, style:"width:100%;height:260px;cursor:pointer", 'data-toggle':"modal", 'data-target':"#modal-photo") %>
                        </div>
                        <div class="col-lg-6 p-2 col-sm-12 col-md-12 page d-block box-shadow">
                          <div class="container h-100">
                            <div class="d-flex align-items-center mb-2">

                              <% if photo.user.avatar.file.nil? %>
                              <a class="btn avatar font-weight-bold rounded-circle p-2" type="button" href="<%=user_path(photo.user_id)%>"><%= "#{photo.user.firstname[0]}#{photo.user.lastname[0]}"%></a>
                              <% else %>
                              <a href="<%=user_path(photo.user_id)%>" ><%= image_tag photo.user.avatar.url, { style:"height:40px;width:40px;",class:"rounded-circle"}%></a>
                              <% end%>

                              <a class="font-weight-bold text-color ml-2 text-decoration-none" href="<%=user_path(photo.user_id)%>"><%= "#{photo.user.firstname} #{photo.user.lastname}" %></a>

                            </div>

                            <span><b><%=photo.title%></b></span>
                            <p class="font-size"><%=photo.description%></p>
                            <div>
                              <span class=<%= if liked?(current_user, photo) then "text-color" else "text-gray" end%> ><i class="fas fa-heart"></i></span>
                               <span class="font-size-sm "><%= photo.likes.size %> </span>
                              <span class="float-right"><small class="text-secondary "><%= photo.created_at.strftime("%I:%M %p %-d/%-m/%Y") %></small></span>
                            </div>
                          </div>
                        </div>
                      </div>
                      <% end %>
                    <% end %>
                </div>
                <div class="row justify-content-center m-2">
                <%= paginate @photos%>
                </div>
              </div>
            </div>
            <div class="col-lg-2"></div>
        </div>
    </div>

  <%= render "modal" %>